// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWrenncblxX5885hCnxxVyleIM0ASBujw',
    appId: '1:1067451480078:web:7495c0c573dd16b746a45f',
    messagingSenderId: '1067451480078',
    projectId: 'share-cost-app',
    authDomain: 'share-cost-app.firebaseapp.com',
    storageBucket: 'share-cost-app.appspot.com',
    measurementId: 'G-Z52Z4JT9Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQSkXpRJgeH9fHp4qcWKIsO1ktXvWPcY',
    appId: '1:1067451480078:android:6f6a55b52252a1fa46a45f',
    messagingSenderId: '1067451480078',
    projectId: 'share-cost-app',
    storageBucket: 'share-cost-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfrsMCAHQsXhgS4qKH2eok2I5gbjD3h08',
    appId: '1:1067451480078:ios:8aaad2d9c00c6ad446a45f',
    messagingSenderId: '1067451480078',
    projectId: 'share-cost-app',
    storageBucket: 'share-cost-app.appspot.com',
    iosClientId: '1067451480078-kbbvdm06eb4jaqdri7gk5efigbq5mtih.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareCostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfrsMCAHQsXhgS4qKH2eok2I5gbjD3h08',
    appId: '1:1067451480078:ios:8aaad2d9c00c6ad446a45f',
    messagingSenderId: '1067451480078',
    projectId: 'share-cost-app',
    storageBucket: 'share-cost-app.appspot.com',
    iosClientId: '1067451480078-kbbvdm06eb4jaqdri7gk5efigbq5mtih.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareCostApp',
  );
}
